version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: muhammad1/exam105-be:${DOCKER_TAG}"
    ports:
      - '9090:9090'
    environment: 
      - ENV_MONGO_USER
      - ENV_MONGO_PASS
      - ENV_MONGO_DEV_IP
      - ENV_MONGO_AUTH_DB
networks:
  default:
    external:
      name: exam105